### ISSUE TITLE
Load Transactions issue : ff_transactions

### ISSUE THREAD

**Issue by BarkovMVP** [ffverse/ffscrapr#299]
**Describe the bug**
**Error in format_error_bullets(x[-1]) : 
  nms %in% c("i", "x", "") are not all TRUE**
**Reprex**
Please provide a short, reproducible example of the code you are trying to run. 
For more on reprexes, check out https://reprex.tidyverse.org
**## Install Package
install.packages("ffscrapr")

## Load Packages
library(ffscrapr)
library(dplyr)
library(tidyr)

## To change, change League ID
FFLM <- ff_connect(platform = "sleeper", league_id = "649647301366755328", season = 2021)

##  League Settings
FFLM_summary <- ff_league(FFLM)
 ff_league(FFLM) %>% str()

## View Settings
str(FFLM_summary)

## View Rosters
ff_rosters(FFLM)

## Load Transactions
ff_transactions(FFLM)

## Change File Export location "C:\\xxxx\\xx\\xx\\x\\FileName.csv"
write.csv(FFLM_rosters,"C:\\Users\\Collin\\Documents\\Fantasy\\FFLM_Rosters_6192021.csv", row.names = FALSE)**

```r
 # Please include the code used for the connection object from `ff_connect()`
```
**Expected behavior**
Load transactions
**Session information**
Please copy the output of `sessionInfo()` into the box below.
```r
**Error in format_error_bullets(x[-1]) : 
  nms %in% c("i", "x", "") are not all TRUE**
```

**Screenshots**

**Additional context**

**Comment by tanho63** [comment]
Hmm, looks like your league does waivers by priority and not by blind bidding, which is throwing this off a bit. Looking now.
