### ISSUE TITLE
401 for pulling specific year of league

### ISSUE THREAD

**Issue by davisderodes** [ffverse/ffscrapr#332]
Hi! Big fan of the package. Thank you so much for supporting. 

Having this really random issue with the following: 

`conn <- espn_connect(season = 2018, league_id = 336277)`
`matchup_response <- espn_getendpoint(conn, view = "mMatchupScore")`

The raw API query: "https://fantasy.espn.com/apis/v3/games/ffl/seasons/2018/segments/0/leagues/336277?view=mMatchupScore" works in a normal browser. 

However, the same code for 2016, 2017, 2019, 2020 does not throw an error. 

I tried going as deep as I could, but couldn't figure out why it's not running.

**Comment by tanho63** [comment]
Hiya! I'm getting some trouble accessing the linked API query, personally - looks like authentication issues and/or the league being private. 

![image](https://user-images.githubusercontent.com/38083823/132148433-b54d0f14-c886-4baf-ac31-db3661f758fe.png)

If you're commish, you can make the league public, or you can look at the vignette on ESPN authentication https://ffscrapr.ffverse.com/articles/espn_authentication.html

**Comment by davisderodes** [comment]
Hi Tan, 

Thanks so much for responding. 

Trying the version with the key (I'll let you know if that works). 

I'm the comish (which is always nice :) ), but the league is set to public (at least according to ESPN). This makes sense because I can access other years without using a key. 

<img width="1218" alt="Screen Shot 2021-09-05 at 9 47 34 PM" src="https://user-images.githubusercontent.com/20303583/132149351-994f6cf3-feab-4cf9-a495-87a0b58a41fc.png">

**Comment by davisderodes** [comment]
Interesting...all the other years are public...but for some reason this old one isn't editable. Will continue with API key. Thank you so much!

<img width="1222" alt="Screen Shot 2021-09-05 at 9 52 02 PM" src="https://user-images.githubusercontent.com/20303583/132149624-dc93dbb3-76b4-448e-af5f-963a069dcee2.png">

**Comment by davisderodes** [comment]
Worked with API key, must be a thing with ESPN that it's immutable? Anyways, thanks man. Good luck next season!

**Comment by tanho63** [comment]
Awesome to hear! Yeah, very possible, ESPN can be ... odd 😝
