### ISSUE TITLE
Clean dp_playerids() team abbreviations

### ISSUE THREAD

**Issue by TheMathNinja** [ffverse/ffscrapr#334]
Not sure if this is a bug or not, but I'm noticing that dp_playerids() default output for `team` is not "clean" according to `nflreadr::clean_team_abbrs()` even though the name variable is "clean" according to nflreadr::clean_player_names(). Seems like we would want this clean?

**Comment by tanho63** [comment]
These line up with MFL which is the primary API source for DynastyProcess. Cleaning can be done with utilities as necessary :)
