### ISSUE TITLE
.espn_stat_map() missing key stats

### ISSUE THREAD

**Issue by scottfrechette** [ffverse/ffscrapr#337]
My league gives a point for every 10 rushing/receiving yards and every 25 passing yards, which seems to be a separate stat than 0.1 /0.04 points per yard in standard leagues (see reprex below). We also have a stat for 22-27 points allowed.

Obviously it's a little more complicated to calculate points with thresholds for ff_scoringhistory.espn_conn but think it should at least be added to .espn_stat_map(). Happy to submit PR if it helps. 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
conn <- ffscrapr::espn_connect(2021, 299999)

ffscrapr::espn_getendpoint(conn, view = "mSettings") %>%
  purrr::pluck("content", "settings", "scoringSettings", "scoringItems") %>%
  tibble::tibble() %>%
  tidyr::unnest_wider(1) %>%
  dplyr::mutate(stat = ffscrapr:::.espn_stat_map()[as.character(.data$statId)] %>% unname()) %>% 
  dplyr::arrange(statId) %>% 
  knitr::kable(align = 'c')
```

| isReverseItem | leagueRanking | leagueTotal | points | pointsOverrides | statId |               stat                |
|:-------------:|:-------------:|:-----------:|:------:|:---------------:|:------:|:---------------------------------:|
|     FALSE     |       0       |      0      |  4.0   |      NULL       |   4    |         passingTouchdowns         |
|     FALSE     |       0       |      0      |  1.0   |      NULL       |   8    |                NA                 |
|     FALSE     |       0       |      0      |  2.0   |      NULL       |   19   |       passing2PtConversions       |
|     FALSE     |       0       |      0      |  -2.0  |      NULL       |   20   |       passingInterceptions        |
|     FALSE     |       0       |      0      |  6.0   |      NULL       |   25   |         rushingTouchdowns         |
|     FALSE     |       0       |      0      |  2.0   |      NULL       |   26   |       rushing2PtConversions       |
|     FALSE     |       0       |      0      |  1.0   |      NULL       |   28   |                NA                 |
|     FALSE     |       0       |      0      |  6.0   |      NULL       |   43   |        receivingTouchdowns        |
|     FALSE     |       0       |      0      |  2.0   |      NULL       |   44   |      receiving2PtConversions      |
|     FALSE     |       0       |      0      |  1.0   |      NULL       |   48   |                NA                 |
|     FALSE     |       0       |      0      |  0.5   |      NULL       |   53   |        receivingReceptions        |
|     FALSE     |       0       |      0      |  6.0   |      NULL       |   63   |      fumbleRecoveryTouchdown      |
|     FALSE     |       0       |      0      |  -2.0  |      NULL       |   72   |            lostFumbles            |
|     FALSE     |       0       |      0      |  4.0   |      NULL       |   77   |     madeFieldGoalsFrom40To49      |
|     FALSE     |       0       |      0      |  3.0   |      NULL       |   80   |     madeFieldGoalsFromUnder40     |
|     FALSE     |       0       |      0      |  -1.0  |      NULL       |   85   |         missedFieldGoals          |
|     FALSE     |       0       |      0      |  1.0   |      NULL       |   86   |          madeExtraPoints          |
|     FALSE     |       0       |      0      |  0.0   |       10        |   89   |      defensive0PointsAllowed      |
|     FALSE     |       0       |      0      |  0.0   |        7        |   90   |    defensive1To6PointsAllowed     |
|     FALSE     |       0       |      0      |  0.0   |        4        |   91   |    defensive7To13PointsAllowed    |
|     FALSE     |       0       |      0      |  0.0   |        1        |   92   |   defensive14To17PointsAllowed    |
|     FALSE     |       0       |      0      |  0.0   |        6        |   93   | defensiveBlockedKickForTouchdowns |
|     FALSE     |       0       |      0      |  0.0   |        2        |   95   |      defensiveInterceptions       |
|     FALSE     |       0       |      0      |  0.0   |        2        |   96   |         defensiveFumbles          |
|     FALSE     |       0       |      0      |  0.0   |        2        |   97   |       defensiveBlockedKicks       |
|     FALSE     |       0       |      0      |  0.0   |        2        |   98   |         defensiveSafeties         |
|     FALSE     |       0       |      0      |  0.0   |        1        |   99   |          defensiveSacks           |
|     FALSE     |       0       |      0      |  6.0   |        6        |  101   |      kickoffReturnTouchdown       |
|     FALSE     |       0       |      0      |  6.0   |        6        |  102   |        puntReturnTouchdown        |
|     FALSE     |       0       |      0      |  0.0   |        6        |  103   |       fumbleReturnTouchdown       |
|     FALSE     |       0       |      0      |  6.0   |        6        |  104   |    interceptionReturnTouchdown    |
|     FALSE     |       0       |      0      |  0.0   |       -1        |  122   |                NA                 |
|     FALSE     |       0       |      0      |  0.0   |       -4        |  123   |   defensive28To34PointsAllowed    |
|     FALSE     |       0       |      0      |  0.0   |       -7        |  124   |   defensive35To45PointsAllowed    |
|     FALSE     |       0       |      0      |  0.0   |       -10       |  125   |     defensive46+PointsAllowed     |
|     FALSE     |       0       |      0      |  5.0   |      NULL       |  198   |     madeFieldGoalsFrom50To59      |
|     FALSE     |       0       |      0      |  5.0   |      NULL       |  201   |     madeFieldGoalsFrom60Plus      |

<sup>Created on 2021-10-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by tanho63** [comment]
hmm, do you have the official names for the NA stats here? happy to take a PR to .espn_stat_map

**Comment by scottfrechette** [comment]
I can't seem to find official names, but I thought something like "passing25Yards" and "rushing10yards" might work. 

I can submit a PR with that and go from there.
