### ISSUE TITLE
Missing 2021 Kicking Stats

### ISSUE THREAD

**Issue by scottfrechette** [ffverse/ffscrapr#342]
It looks like player_kicking_stats.* files aren't being updated for 2021 season, so functions like `ff_scoringhistory()` don't include kickers. I saw a note not to post issues to that repo so I'm putting it here for downstream effects. 

``` r
library(ffscrapr)

nflfastr_weekly(seasons = 2021, type = "kicking")
#> Empty data.table (0 rows and 40 cols): season,week,season_type,team,player_name,player_id...
```

<sup>Created on 2021-10-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by tanho63** [comment]
This should be resolved as of nflverse/nflfastR-data@8332753
