### ISSUE TITLE
ff_draftpicks returning Error 

### ISSUE THREAD

**Issue by stranger9977** [ffverse/ffscrapr#352]
**Describe the bug**
When calling ff_draftpicks for a sleeper league in 2022 I am getting an error related to the 'metadata column' (see image) 

**Reprex**
Please provide a short, reproducible example of the code you are trying to run. 

```r
ssb <- ff_connect(platform = "sleeper", league_id = "784453846419283968", season = 2022)
```
**Expected behavior**
I expected a table to return with users and their corresponding draft capital from sleeper api. 

**Session information**
Please copy the output of `sessionInfo()` into the box below.
```r
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ffscrapr_1.4.7.02

loaded via a namespace (and not attached):
 [1] compiler_4.0.5    pillar_1.7.0      prettyunits_1.1.1 remotes_2.4.0    
 [5] tools_4.0.5       pkgbuild_1.2.0    jsonlite_1.8.0    memoise_2.0.1    
 [9] lifecycle_1.0.1   tibble_3.1.6      pkgconfig_2.0.3   rlang_1.0.2      
[13] DBI_1.1.1         cli_3.2.0         rstudioapi_0.13   curl_4.3.2       
[17] xfun_0.23         fastmap_1.1.0     withr_2.4.2       httr_1.4.2       
[21] dplyr_1.0.8       generics_0.1.2    vctrs_0.4.0       rprojroot_2.0.2  
[25] tidyselect_1.1.2  glue_1.6.2        R6_2.5.1          processx_3.5.2   
[29] fansi_1.0.3       tidyr_1.2.0       callr_3.7.0       ratelimitr_0.4.1 
[33] purrr_0.3.4       magrittr_2.0.3    ps_1.6.0          ellipsis_0.3.2   
[37] assertthat_0.2.1  tinytex_0.32      utf8_1.2.2        cachem_1.0.6     
[41] crayon_1.5.1    ```

**Screenshots**

**Additional context**
Add any other context about the problem here.
![Screen Shot 2022-04-11 at 8 53 42 PM](https://user-images.githubusercontent.com/86253003/162856888-d58acf01-cb71-4004-9165-0bc9c8262282.png)

**Comment by stranger9977** [comment]
![Screen Shot 2022-04-11 at 8 49 52 PM](https://user-images.githubusercontent.com/86253003/162856990-bedae8f0-84cb-414f-9305-3551f8796f91.png)

**Comment by tanho63** [comment]
It looks like Sleeper's API has changed and doesn't return picks until after the draft has already started, which is really quite shitty I think. See:

```r
httr::GET("https://api.sleeper.app/v1/draft/786958282513362945")
httr::GET("https://api.sleeper.app/v1/draft/786958282513362945/picks")
```

**Comment by stranger9977** [comment]
I was hoping 
```httr::GET("https://api.sleeper.app/v1/draft/786958282513362945/picks")``` 
would return of list of all the picks but you are correct. The list is empty because the drat hasn't happened. That's a bummer. The workaround I'm trying now (in python) is to get the draft order from
`httr::GET("https://api.sleeper.app/v1/draft/786958282513362945"), then use the league details to get the number of rounds in the rookie draft for a given league. Once I have that I loop through the draft order "n" times where n = # of rounds in draft * 3years. This gives me back a draft order for the next three years (the specific order only really matters for 2022). The next move is to assign a season, round, and pick for 2022 picks, and a season and round for 2023 and 2024 picks. I have gotten this far. The next step, which I am struggling with, is using the Get Traded Picks API call to get a data frame with all of the picks that have been traded and use that to reorder the draft accordingly. Im close, but it is pretty tough. I touched base with the creator of dynastyranker.com and he advised me that he solved the problem this way using C#. Hopefully this helps you rebuild the function in a way that works, but it would be nice for Sleeper to revert that change. 
`

**Comment by tanho63** [comment]
Yeah, that sounds about right - I already implement the traded picks logic for future picks, so it would need extending to this year

**Comment by joeflan** [comment]
I'm not sure if this is related, but I was going to open another issue for a similar problem. `ff_draftpicks` is returning an error for sleeper:

`Error in list2(...) : object 'current_picks' not found`

It looks like it's an error in the sleeper_draftpicks.R file here:

https://github.com/ffverse/ffscrapr/blob/0a0f05d9dc00a33f09956bf6c4a1d5ebe2b17963/R/sleeper_draftpicks.R#L36

`current_picks` no longer exists as of the last commit to the file. I haven't tested the issue locally yet

**Comment by tanho63** [comment]
Oh whoops, I must have smushed in broken code there and it's not yet stable. I'm away for a while yet but will try to fix in the next few weeks (i.e. after rsconf but before I start new job). 

Would be happy to review a PR if you're keen but no pressure there @joeflan

**Comment by joeflan** [comment]
I've tested locally and can't reproduce the issue. Sleeper API was likely updated for the new league year.
