### ISSUE TITLE
Cannot access Auction Bid data for MFL

### ISSUE THREAD

**Issue by TheMathNinja** [ffverse/ffscrapr#354]
I'm running 

`ff_transactions(mfl_connect(season = 2021, league_id = 22686,  rate_limit_number = 3, rate_limit_seconds = 6)`

in the hopes of analyzing the bid amounts at which players were won via auction. But ff_transactions() apparently no longer returns auction bid amounts (it did last year). I'm wondering if this is because it's drawing on "Transactions" from MFL rather than "All Transactions" (which include all auction bids). Was this functionality offloaded to another function or might this function just need to be expanded in order to catch winning bids? Thanks.

**Comment by tanho63** [comment]
Have not had time to investigate but if API has changed ffscrapr code will need a corresponding update
