### ISSUE TITLE
Update devel install instructions on pkgdown main

### ISSUE THREAD

**Issue by TheMathNinja** [ffverse/ffscrapr#359]
This is what happens when I try to download the dev version. 

```
> remotes::install_github("ffverse/ffscrapr", ref = "dev")
Downloading GitHub repo ffverse/ffscrapr@dev
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/ffverse/ffscrapr/tarball/dev'
```

**Comment by tanho63** [comment]
Ah yes I stopped using a dev branch and main is now the dev branch

**Comment by TheMathNinja** [comment]
Does this mean there's only one version, the CRAN version, or would using ref = "main" get me a more updated version that hasn't been released to CRAN yet?

**Comment by tanho63** [comment]
the latter. I used to keep GitHub main as equal to CRAN but I've stopped seeing the value in it, instead preferring to use GitHub releases for CRAN versioning if people want a backup install

**Comment by tanho63** [comment]
for reference, 

`remotes::install_github("ffverse/ffscrapr")` is equivalent to `remotes::install_github("ffverse/ffscrapr", ref = "main")`

**Comment by TheMathNinja** [comment]
Great, thanks! Yeah, looks like ffscrapr homepage just needs a slight edit then.

**Comment by tanho63** [comment]
Oh right that wouldn’t update til CRAN release otherwise
