### ISSUE TITLE
ffscrapr for Sleeper Mocks

### ISSUE THREAD

**Issue by nickpietrantonio** [ffverse/ffscrapr#360]
Sorry if this isn't really a bug, I'm wondering if you can scrape Sleeper mock drafts with ffscrapr. 
The following is the code I am trying. With or without a username produced the same error. 
```
library(ffscrapr)
library(dplyr)
ff_connect(platform = "Sleeper", league_id = 845064096834514944, season = 2022) %>% 
    ff_draft()
#> Error in `stop_subscript()`:
#> ! Can't extract columns that don't exist.
#> x Column `metadata` doesn't exist.
```

The URL for the mock is here: https://sleeper.com/draft/nfl/845064096834514944
I just grabbed the end of the URL as the league_id since its the same character count as other leagues I have seen, but this may be the incorrect way to go about this as I am fairly new to sleeper.

**Comment by tanho63** [comment]
Hmm - draft_id is not the same as league_id...so you may be able to use some of the underlying functions to get at this

```r
ffscrapr:::.sleeper_currentdraft("845064096834514944")
```
```
# A tibble: 184 x 4
   round  pick franchise_id player_id
   <int> <int> <lgl>        <chr>    
 1     1     1 NA           4984     
 2     1     2 NA           6797     
 3     1     3 NA           7553     
 4     1     4 NA           4046     
 5     1     5 NA           6770     
 6     1     6 NA           5849     
 7     1     7 NA           4881     
 8     1     8 NA           6813     
 9     1     9 NA           1466     
10     1    10 NA           4034     
# ... with 174 more rows
```
You'll also need to left join on `sleeper_players()` via `player_id`, and I don't think you'll be able to get at the franchises conveniently without making custom API requests

**Comment by tanho63** [comment]
I'm unsure at this time whether it makes sense to rewrite ff_draft (and really all the sleeper functions) in a way that does not require the conn object. It would be a rather large undertaking.

**Comment by nickpietrantonio** [comment]
For what I am trying to do here at least, this is perfect, thank you! I'm trying to get an adp for some SFB12 mocks so franchises aren't necessary.
