### ISSUE TITLE
MFL API change for ff_standings()

### ISSUE THREAD

**Issue by TheMathNinja** [ffverse/ffscrapr#366]
I just wanted to post a news point here. This was published by MFL on July 25. I'm thinking a few ffscrapr functions are impacted:

We have maintained our Developers API fairly static over the past couple of years. Here's a rundown of changes that are in effect for 2022:

The export standings API call will no longer return any data. This function was deprecated years ago and replaced with leagueStandings but was kept in place for backward compatibility. Due to recent internal changes to our data, it's not longer compatible so we have removed it.
The Partial Lineup Allowed setting is now returned on the export league API call. The value can be YES or NO.
Added the export abilities API. It returns the state of the various abilities for each franchise. Values are either 1 (franchise has ability) or 0 (franchise does not have ability). It should be straight-forward to match abilities ids in the response to those displayed on the Commissioner Setup > Abilities Setup page.
The export leagueStandings API will now return the same set of columns as the Standings Report on the web site with a few of exceptions: The STRK (Streak), GB (Games Behind) and PB (Points Behind) columns are not going to appear on the API. The reason for this is a due to the way the code was written many years ago and fixing it would likely introduce new issues. In addition, the icon/logo columns will not appear either. This information is available via the league call. Custom columns will be returned via the API.
The export leagueStandings API accepts a new paramenter COLUMN_NAMES than when set it will return the column labels for each column in the standings report. This is useful for dealing with leagues that have custom columns as this allows labeling those columns.
This notice was last updated on July 25, 2022.

**Comment by tanho63** [comment]
https://github.com/ffverse/ffscrapr/blob/0a0f05d9dc00a33f09956bf6c4a1d5ebe2b17963/R/mfl_standings.R#L20

looks like we should be safe on league standings since we're already using the recommended leagueStandings endpoint. other changes should be guarded against but we'll need to keep an eye on it probably

**Comment by tanho63** [comment]
TODO:

- [ ] evaluate how to handle MFL standings now that columns returned can be affected by user/commissioner decisions
