### ISSUE TITLE
dp_clean_names() updates needed

### ISSUE THREAD

**Issue by TheMathNinja** [ffverse/ffscrapr#377]
The current function doesn't catch these issues:

Ken Walker -> Kenneth Walker
Joe Tryon -> Joe Tryon-Shoyinka
Darius Leonard -> Shaquille Leonard

Capitalizations that happen mid-name, i.e. "DeMario Davis" should get cleaned to "Demario Davis"

**Comment by tanho63** [comment]
Closing, since this should be tracked in nflverse/nflreadr. 

The only option for cases is to switch to lowercase, or no change applied, so the latter will not be included in this function (even in nflreadr). This is another easy CSV-based PR when you’re over there though.
