### ISSUE TITLE
ff_schedule two rows per matchup (Sleeper)

### ISSUE THREAD

**Issue by christianlohr9** [ffverse/ffscrapr#378]
Yo Tan,

when scraping the schedule via `ff_schedule()` the output provides two rows per matchup, one with each user the "home team".
This could be by purpose, so I don't know if it's a bug, but for my understanding one row per matchup (so in a 12 team league 6 rows instead of 12) feel "more correct".

Thx for your support!

Below the reprex. As u can see in row 1 and 3 there is the same matchup for instance.

**Reprex**
``` r
library(tidyverse)
ffscrapr::ff_schedule(
  ffscrapr::sleeper_connect(season = 2022, league_id = "861018918574211072")
)
#> # A tibble: 168 × 6
#>     week franchise_id franchise_score opponent_id opponent_score result
#>    <int>        <int>           <dbl>       <int>          <dbl> <chr> 
#>  1     1            1             0             3           45.5 <NA>  
#>  2     1            2             0            11           25.6 <NA>  
#>  3     1            3            45.5           1            0   <NA>  
#>  4     1            4            -4.2           7            0   <NA>  
#>  5     1            5             0            10           49.1 <NA>  
#>  6     1            6             0             9            0   <NA>  
#>  7     1            7             0             4           -4.2 <NA>  
#>  8     1            8             0            12            0   <NA>  
#>  9     1            9             0             6            0   <NA>  
#> 10     1           10            49.1           5            0   <NA>  
#> # … with 158 more rows
```

<sup>Created on 2022-09-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by tanho63** [comment]
This is intentional <https://ffscrapr.ffverse.com/reference/ff_schedule.html> - one row for every team for every matchup/week. It makes for easy summaries (group_by franchise id, then summarise franchise_score and/or results)
