### ISSUE TITLE
ff_rosters() row duplication (roster_status issue)

### ISSUE THREAD

**Issue by TheMathNinja** [ffverse/ffscrapr#394]
Code:

ff_rosters(mfl_connect(season = 2016, league_id = 60206))

returns two rows of Rob Ninkovich (player_id == 8376) in the NFC conference, one with roster_status of ROSTER and one of INJURED_RESERVE.

The INJURED_RESERVE entry appears to be a bug. He cannot be both on the roster and on IR. He is not on IR on the league page itself. Not sure where this is coming from.

**Comment by tanho63** [comment]
This looks like an API issue https://api.myfantasyleague.com/2016/export?TYPE=rosters&L=60206&APIKEY=&FRANCHISE=&W=&JSON=1

you’d need to clean it after the api call, or I guess you could write to MFL and get them to fix an API response from seven years ago. in either case there’s nothing in package scope to do here
