### ISSUE TITLE
Map "Nathaniel Dell" to "Tank Dell"

### ISSUE THREAD

**Issue by TheMathNinja** [ffverse/ffscrapr#404]
I think `nflreadr::clean_player_names()` should be mapping "Nathaniel Dell" to "Tank Dell". 

As a bonus, this isn't in the documentation yet for nflreadr::player_name_mapping() but listing the standard name this function converts to would be helpful (NFL.com seems reasonable?). That's what I'm using here.

**Comment by tanho63** [comment]
> I think nflreadr::clean_player_names() should be mapping "Nathaniel Dell" to "Tank Dell".

so this probably should be filed in nflreadr
