### ISSUE TITLE
Request Season parameter be added to FleaFlicker endpoints

### ISSUE THREAD

**Issue by RandalMorris** [ffverse/ffscrapr#405]
When using ff_franchises for example, the FetchLeagueStandings endpoint accepts season as a parameter, but the package isn't passing it from the connection dataset. It defaults to current season so even if the connection data has 2022, it is pulling 2023

**Comment by tanho63** [comment]
Hmm. This looks like a pretty straightforward addition- do you want to give it a go in a PR?

**Comment by RandalMorris** [comment]
I changed the R/flea_franchises.R to  fleaflicker_getendpoint("FetchLeagueStandings", season = conn$season,  league_id = conn$league_id, sport = "NFL").  Still pulls 2023, I even manually set it to 2022. 

When I create the function locally, it works so i am missing something.

**Comment by tanho63** [comment]
hmm. may need to restart R to make sure it’s not being cached

**Comment by RandalMorris** [comment]
That did it, I thought i had tried that lol. 

I will submit a PR soon. I am going through them to add that where it can be used.

**Comment by tanho63** [comment]
Gonna keep this open and close it when the appropriate PR is merged into main

**Comment by tanho63** [comment]
Resolved in #408
