### ISSUE TITLE
ff_transactions() behind on sleeper

### ISSUE THREAD

**Issue by joshbis** [ffverse/ffscrapr#419]
**Describe the bug**
The most recent transaction being pulled for sleeper is seemingly 2023-11-09 17:20:12 [current sys.time() is 2023-11-12 20:55:11]

Unclear whether this is an issue with the Sleeper API or the ff_connect() package. 

```r
Running this as:
league_id <- "932553828120104960"
slp <- ff_connect(platform = "sleeper", league_id = league_id, season = 2023)
transactions <- data.table(ff_transactions(slp))

**Comment by tanho63** [comment]
I’m guessing this is api related, is it normal this morning?

**Comment by joshbis** [comment]
Still looks stalled ... fwiw, ff_rosters() is current [it shows someone who was picked up on Sunday]

**Comment by tanho63** [comment]
I'm going to close out this as an odd API issue. If this becomes an issue in the future, we can investigate sleeper api by checking the transaction endpoint https://docs.sleeper.com/#get-transactions and showing that the API is returning correctly but ffscrapr handling the response incorrectly.
