### ISSUE TITLE
franchise_name column returning NA NA when I run ff_franchises / ff_rosters

### ISSUE THREAD

**Issue by SahilTilak** [ffverse/ffscrapr#420]
**Describe the bug**
I'm trying to use ffverse, however the functions are not able to return the names of teams, they all just say NA NA

``` r
ffscrapr::ff_franchises(ffscrapr::espn_connect(season = 2023, 
    league_id = 758277075))
#> # A tibble: 12 × 8
#>    franchise_id franchise_name franchise_abbrev logo        waiver_order user_id
#>           <int> <chr>          <chr>            <chr>              <int> <chr>  
#>  1            1 NA NA          TILA             https://g.…            9 {9C2A7…
#>  2            2 NA NA          DALE             https://i.…            4 {064D4…
#>  3            5 NA NA          SALT             https://g.…            7 {4EA83…
#>  4            6 NA NA          ONTI             https://ww…            1 {3B55F…
#>  5            8 NA NA          DU               https://g.…           12 {1F8C1…
#>  6            9 NA NA          MYER             https://g.…            3 {779F6…
#>  7           10 NA NA          LI               https://g.…            5 {7A9F4…
#>  8           11 NA NA          TSAI             https://g.…           10 {8C540…
#>  9           12 NA NA          VERM             https://g.…           11 {B991B…
#> 10           13 NA NA          TEd              https://g.…            2 {77281…
#> 11           14 NA NA          WILS             https://g.…            6 {E9C93…
#> 12           15 NA NA          TROD             https://g.…            8 {6A557…
#> # ℹ 2 more variables: user_name <chr>, user_nickname <chr>
```

<sup>Created on 2023-11-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by tanho63** [comment]
Please provide the output of nflreadr::ffverse_sitrep()

**Comment by SahilTilak** [comment]
nflreadr::ffverse_sitrep()
#> ℹ You've asked for the packages ffpros and ffopportunity which are not installed. 
#> They are skipped.
#> ── System Info ─────────────────────────────────────────────────────────────────
#> • R version 4.2.2 (2022-10-31)   • Running under: macOS 14.0
#> ── ffverse Packages ────────────────────────────────────────────────────────────
#> • ffscrapr    (1.4.8)
#> • ffsimulator (1.2.3)
#> ── ffverse Options ─────────────────────────────────────────────────────────────
#> No options set for ffscrapr and ffsimulator
#> ── ffverse Dependencies ────────────────────────────────────────────────────────
#> • askpass    (1.1)     • httr       (1.4.5)  • Rglpk      (0.6-5)   
#> • assertthat (0.2.1)   • jsonlite   (1.8.4)  • rlang      (1.1.0)   
#> • backports  (1.4.1)   • lifecycle  (1.0.3)  • slam       (0.1-50)  
#> • cachem     (1.0.6)   • magrittr   (2.0.3)  • stringi    (1.7.12)  
#> • checkmate  (2.3.0)   • memoise    (2.0.1)  • stringr    (1.5.0)   
#> • cli        (3.6.1)   • mime       (0.12)   • sys        (3.4.1)   
#> • cpp11      (0.4.3)   • nflreadr   (1.3.2)  • tibble     (3.2.1)   
#> • curl       (5.0.0)   • openssl    (2.0.6)  • tidyr      (1.3.0)   
#> • data.table (1.14.8)  • pillar     (1.9.0)  • tidyselect (1.2.0)   
#> • dplyr      (1.1.2)   • pkgconfig  (2.0.3)  • tidytable  (0.10.2)  
#> • fansi      (1.0.4)   • purrr      (1.0.1)  • utf8       (1.2.3)   
#> • fastmap    (1.1.0)   • R6         (2.5.1)  • vctrs      (0.6.2)   
#> • generics   (0.1.3)   • rappdirs   (0.3.3)  • withr      (2.5.0)   
#> • glue       (1.6.2)   • ratelimitr (0.4.1)    
#> ────────────────────────────────────────────────────────────────────────────────
Created on 2023-11-14 with [reprex v2.0.2](https://reprex.tidyverse.org/)

**Comment by SahilTilak** [comment]
``` r
nflreadr::ffverse_sitrep()
#> ── System Info ─────────────────────────────────────────────────────────────────
#> • R version 4.3.1 (2023-06-16) • Running under: Ubuntu 22.04.3 LTS
#> ── Package Status ──────────────────────────────────────────────────────────────
#>       package installed  cran      dev behind
#> 1    ffscrapr     1.4.8 1.4.8 1.4.8.14    dev
#> 2 ffsimulator     1.2.3 1.2.3 1.2.3.01    dev
#> ── Package Options ─────────────────────────────────────────────────────────────
#> • No options set for above packages
#> ── Package Dependencies ────────────────────────────────────────────────────────
#> • nflreadr   (1.4.0)   • fastmap   (1.1.1)  • stringi    (1.7.12)  
#> • ratelimitr (0.4.1)   • generics  (0.1.3)  • stringr    (1.5.0)   
#> • Rglpk      (0.6-5)   • glue      (1.6.2)  • sys        (3.4.2)   
#> • slam       (0.1-50)  • httr      (1.4.7)  • tibble     (3.2.1)   
#> • tidytable  (0.10.1)  • jsonlite  (1.8.7)  • tidyr      (1.3.0)   
#> • askpass    (1.2.0)   • lifecycle (1.0.3)  • tidyselect (1.2.0)   
#> • assertthat (0.2.1)   • magrittr  (2.0.3)  • utf8       (1.2.3)   
#> • backports  (1.4.1)   • memoise   (2.0.1)  • vctrs      (0.6.3)   
#> • cachem     (1.0.8)   • mime      (0.12)   • withr      (2.5.0)   
#> • checkmate  (2.2.0)   • openssl   (2.1.0)  • graphics   (4.3.1)   
#> • cli        (3.6.1)   • pillar    (1.9.0)  • grDevices  (4.3.1)   
#> • cpp11      (0.4.6)   • pkgconfig (2.0.3)  • methods    (4.3.1)   
#> • curl       (5.0.2)   • purrr     (1.0.2)  • stats      (4.3.1)   
#> • data.table (1.14.8)  • R6        (2.5.1)  • tools      (4.3.1)   
#> • dplyr      (1.1.3)   • rappdirs  (0.3.3)  • utils      (4.3.1)   
#> • fansi      (1.0.4)   • rlang     (1.1.1)    
#> ── Not Installed ───────────────────────────────────────────────────────────────
#> • ffpros        ()
#> • ffopportunity ()
#> ────────────────────────────────────────────────────────────────────────────────
```

<sup>Created on 2023-11-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by tanho63** [comment]
Please install latest development version and retry

**Comment by SahilTilak** [comment]
Yes, that worked for me.
