### ISSUE TITLE
ff_standings() for MFL significantly diminished

### ISSUE THREAD

**Issue by TheMathNinja** [ffverse/ffscrapr#430]
In the past, the ff_standings() function returned potential_points, offensive_points, and defensive_points. But currently, I'm only seeing Points For and Points against in the points readouts. Can we re-include offense, defense, potential for MFL in this function? Thanks!

Additionally (or even instead-of), it would equally help my purposes if ff_schedule() included these numbers on a week-by-week basis.

**Comment by tanho63** [comment]
Have you modified the standings columns in commissioner standings? I think it’s at least partially impacted by what you select there

**Comment by TheMathNinja** [comment]
I'm seeing that now, yes. Ok, I think this is different than before, but yes it looks constrained by what I choose to have displayed. Is there a way for this function to default to a full readout of all columns that are possible, or to have a full_readout = TRUE argument to have that option?

I guess I'd like ffscrapr to return all 50 variables possible or whatever, but no way I want 50 columns on my MFL standings report.

**Comment by tanho63** [comment]
please provide output of `ffscrapr::ffverse_sitrep()`

**Comment by TheMathNinja** [comment]
```
── System Info ────────────────────────────────────────────────────────────────
• R version 4.4.1 (2024-06-14 ucrt) • Running under: Windows 11 x64 (build 22631)
── Package Status ─────────────────────────────────────────────────────────────
   package installed  cran      dev behind
1 ffscrapr  1.4.8.18 1.4.8 1.4.8.18       
── Package Options ────────────────────────────────────────────────────────────
• No options set for above packages
── Package Dependencies ───────────────────────────────────────────────────────
• askpass    (1.2.0)   • jsonlite   (1.8.8)     • stringr    (1.5.1)  
• assertthat (0.2.1)   • lifecycle  (1.0.4)     • sys        (3.4.2)  
• backports  (1.5.0)   • magrittr   (2.0.3)     • tibble     (3.2.1)  
• cachem     (1.1.0)   • memoise    (2.0.1)     • tidyr      (1.3.1)  
• checkmate  (2.3.1)   • mime       (0.12)      • tidyselect (1.2.1)  
• cli        (3.6.3)   • nflreadr   (1.4.0.12)  • utf8       (1.2.4)  
• cpp11      (0.4.7)   • openssl    (2.2.0)     • vctrs      (0.6.5)  
• curl       (5.2.1)   • pillar     (1.9.0)     • withr      (3.0.0)  
• data.table (1.15.4)  • pkgconfig  (2.0.3)     • graphics   (4.4.1)  
• dplyr      (1.1.4)   • purrr      (1.0.2)     • grDevices  (4.4.1)  
• fansi      (1.0.6)   • R6         (2.5.1)     • methods    (4.4.1)  
• fastmap    (1.2.0)   • rappdirs   (0.3.3)     • stats      (4.4.1)  
• generics   (0.1.3)   • ratelimitr (0.4.1)     • tools      (4.4.1)  
• glue       (1.7.0)   • rlang      (1.1.4)     • utils      (4.4.1)  
• httr       (1.4.7)   • stringi    (1.8.4)       
── Not Installed ──────────────────────────────────────────────────────────────
• ffsimulator  • ffpros  • ffopportunity  
```

**Comment by tanho63** [comment]
and reprex?

**Comment by tanho63** [comment]
https://www43.myfantasyleague.com/2022/api_info?STATE=test&CCAT=export&TYPE=leagueStandings&L=22686

if you put the ALL parameter here = 1 or = 0, it returns the same columns, so I think that portion of the API is broken. You may need to open an MFL help ticket demonstrating this
